repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Nucleoid"
        url = "https://maven.nucleoid.xyz/releases"
    }
}

loom {
    mixin {
        useLegacyMixinAp.set(false)
    }
}

architectury {
    platformSetupLoomIde()
    fabric()
}

dependencies {
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"

    implementation project(':common')

    compileOnly "eu.pb4:trinkets:4.1.0-beta.2+26.2"
    localRuntime "eu.pb4:trinkets:4.1.0-beta.2+26.2"

    localRuntime "maven.modrinth:appleskin:3.0.10+mc26.2"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(':common').sourceSets.main.output
}
